---
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Naming/FileName:
  Enabled: true
  Exclude:
    - lib/asciidoctor-plantuml.rb

Metrics/MethodLength:
  Max: 50

Metrics/ClassLength:
  Max: 250
  Exclude:
    - test/test_plantuml.rb

Metrics/AbcSize:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Layout/LineLength:
  Max: 120
